### ISSUE TITLE
Add link to the STAMINA repository 

### ISSUE THREAD

**Issue by zgzn** [formal-verification-research/formal-verification-research.github.io#1]
Add a link to the STAMINA project on another repository: https://github.com/fluentverification/stamina
Also, create a link to STAMINA on our research group Github repository.

**Comment by landonjefftaylor** [comment]
I haven't been able to find a way to add the entire repository to our list on Github. I added a link on the webpage in the introduction section. I don't have access to the settings for this organization, but we can add formal-verificatoin-research.github.io as our URL.
I could also create a repository that just has a readme linking to the STAMINA repository.
