### ISSUE TITLE
Copy BibTeX button copies invalid BibTeX file

### ISSUE THREAD

**Issue by zgzn** [formal-verification-research/formal-verification-research.github.io#2]
Clicking on this button creates an invalid BibTeX entry. See the contents below as an example:
						{'year': '2021',
						'journal': 'International Symposium on Leveraging Applications of Formal Methods ({ISoLA})',
						'url': 'https://digitalcommons.usu.edu/ece_facpub/230/',
						'title': 'On Correctness, Precision, and Performance in Quantitative Verification',
						'publisher': 'Springer International Publishing',
						'pages': '216--241',
						'isbn': '978-3-030-83723-5',
						'editor': 'Margaria, Tiziana and Steffen, Bernhard',
						'booktitle': 'Leveraging Applications of Formal Methods, Verification and Validation: Tools and Trends',
						'author+an': '2=corresponding; 8=group',
						'author': "Budde, Carlos E. and Hartmanns, Arnd and Klauck, Michaela and K{\\v{r}
					}et{\\'{i}
					}nsk{\\'y}, Jan and Parker, David and Quatmann, Tim and Turrini, Andrea and Zhang, Zhen", 'ENTRYTYPE': 'inproceedings',
						'ID': 'Budde2021'}

**Comment by landonjefftaylor** [comment]
This was a bug with the Python module bibtexparser. It should be resolved.
